#2/14/2020
#This puzzle requires some basic numerical manipulation on a set of numbers
#This part also requires recursively adding extra fuel for the weight of the fuel generated by the equation

import math

def calcFuel(weight):
	fuel = math.floor(weight / 3) - 2
	if fuel < 0:
		return 0
	else:
		return fuel + calcFuel(fuel)


input = open("input.txt")
data = input.read()


total = 0
for value in data.splitlines():
	total += calcFuel(int(value))

print("Fuel Required:", total)

#Correct answer: 5049684